name: Full CI/CD Django to Azure

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test


  build:
    runs-on: ubuntu-latest
    needs: test                         
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
            --username ${{ secrets.ACR_USERNAME }} \
            --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/django-app:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/django-app:${{ github.sha }}


  deploy-app-service:
    runs-on: ubuntu-latest
    needs: build                      
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to App Service
        run: |
          az webapp config container set \
            --name ${{ secrets.WEBAPP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/django-app:${{ github.sha }} \
            --docker-registry-server-url https://${{ secrets.ACR_LOGIN_SERVER }}

      - name: Restart App Service
        run: |
          az webapp restart \
            --name ${{ secrets.WEBAPP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }}


  deploy-aks:
    runs-on: ubuntu-latest
    needs: build                    
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/django-app \
            django-app=${{ secrets.ACR_LOGIN_SERVER }}/django-app:${{ github.sha }}
